def handle_nl_cmd(nl_cmd):
    cmd = nl_cmd.lower()
    rules = [
        ((["list", "file"], "ls")),
        ((["show", "hidden", "file"], "ls -a")),
        ((["kill", "chrome"], "pkill chrome")),
        ((["get", "ip"], "hostname -I")),
        ((["clean", "temp"], "rm -rf /tmp/*")),
        ((["system", "info"], "uname -a && free -h && lsb_release -a")),
        ((["who", "am", "i"], "whoami")),
        ((["list", "user"], "cut -d: -f1 /etc/passwd")),
        ((["uptime"], "uptime")),
        ((["ping", "google"], "ping google.com")),
        ((["open", "file", "explorer"], "xdg-open .")),
        ((["current", "directory"], "pwd")),
        ((["disk", "usage"], "df -h")),
        ((["memory", "usage"], "free -h")),
        ((["cpu", "info"], "lscpu")),
        ((["network", "info"], "ifconfig || ip a")),
        ((["delete", "file"], "rm <filename>")),
        ((["copy", "file"], "cp <source> <destination>")),
        ((["move", "file"], "mv <source> <destination>")),
        ((["make", "directory"], "mkdir <dirname>")),
        ((["remove", "directory"], "rmdir <dirname>")),
        ((["list", "process"], "ps aux")),
        ((["kill", "process"], "pkill <processname>")),
        ((["install", "package"], "sudo apt install <package>")),
        ((["update", "system"], "sudo apt update && sudo apt upgrade")),
        ((["show", "open", "ports"], "netstat -tuln")),
        ((["firewall", "status"], "sudo ufw status")),
        ((["user", "info"], "id <username>")),
        ((["logout"], "logout")),
        ((["shutdown"], "sudo shutdown now")),
        ((["reboot"], "sudo reboot")),
        ((["search", "file"], "find . -name '<filename>'")),
        ((["download", "file"], "wget <url>")),
        ((["edit", "file"], "nano <filename>")),
        ((["show", "calendar"], "cal")),
        ((["date", "time"], "date")),
        ((["show", "history"], "history")),
        ((["clear", "screen"], "clear")),
        ((["change", "password"], "passwd")),
        ((["list", "services"], "systemctl list-units --type=service")),
        ((["start", "service"], "sudo systemctl start <service>")),
        ((["stop", "service"], "sudo systemctl stop <service>")),
        ((["restart", "service"], "sudo systemctl restart <service>")),
        ((["status", "service"], "systemctl status <service>")),
        ((["list", "groups"], "getent group")),
        ((["add", "user"], "sudo adduser <username>")),
        ((["delete", "user"], "sudo deluser <username>")),
        ((["list", "mounted"], "mount | column -t")),
        ((["show", "env"], "printenv")),
    ]
    for keywords, command in rules:
        if all(word in cmd for word in keywords):
            return command
    return f'echo Linux: {nl_cmd}'