def handle_nl_cmd(nl_cmd):
    cmd = nl_cmd.lower()
    rules = [
        ((["list", "file"], "dir")),
        ((["show", "hidden", "file"], "dir /a")),
        ((["kill", "chrome"], "taskkill /IM chrome.exe /F")),
        ((["get", "ip"], "ipconfig")),
        ((["clean", "temp"], r"del /q/f/s %TEMP%\*")),
        ((["system", "info"], "systeminfo")),
        ((["who", "am", "i"], "whoami")),
        ((["list", "user"], "net user")),
        ((["uptime"], "net stats srv")),
        ((["ping", "google"], "ping google.com")),
        ((["open", "file", "explorer"], "explorer .")),
        ((["current", "directory"], "cd")),
        ((["disk", "usage"], "wmic logicaldisk get size,freespace,caption")),
        ((["memory", "usage"], "systeminfo | findstr /C:\"Total Physical Memory\" /C:\"Available Physical Memory\"")),
        ((["cpu", "info"], "wmic cpu get name,NumberOfCores,NumberOfLogicalProcessors")),
        ((["network", "info"], "ipconfig /all")),
        ((["create", "file"], "echo. > <filename>")),
        ((["new", "file"], "echo. > <filename>")),
        ((["make", "file"], "echo. > <filename>")),
        ((["touch", "file"], "echo. > <filename>")),
        ((["create", "empty", "file"], "echo. > <filename>")),
        ((["delete", "file"], "del <filename>")),
        ((["copy", "file"], "copy <source> <destination>")),
        ((["move", "file"], "move <source> <destination>")),
        ((["make", "directory"], "mkdir <dirname>")),
        ((["create", "directory"], "mkdir <dirname>")),
        ((["create", "folder"], "mkdir <dirname>")),
        ((["new", "folder"], "mkdir <dirname>")),
        ((["make", "folder"], "mkdir <dirname>")),
        ((["remove", "directory"], "rmdir <dirname>")),
        ((["list", "process"], "tasklist")),
        ((["kill", "process"], "taskkill /IM <processname> /F")),
        ((["install", "package"], "winget install <package>")),
        ((["update", "system"], "wuauclt /detectnow")),
        ((["show", "open", "ports"], "netstat -aon")),
        ((["firewall", "status"], "netsh advfirewall show allprofiles")),
        ((["user", "info"], "net user <username>")),
        ((["logout"], "shutdown /l")),
        ((["shutdown"], "shutdown /s /t 0")),
        ((["reboot"], "shutdown /r /t 0")),
        ((["search", "file"], "dir /s /b <filename>")),
        ((["download", "file"], "powershell -Command \"Invoke-WebRequest -Uri <url> -OutFile <filename>\"")),
        ((["edit", "file"], "notepad <filename>")),
        ((["show", "calendar"], "powershell -Command \"Get-Date\"")),
        ((["date", "time"], "time /t & date /t")),
        ((["show", "history"], "doskey /history")),
        ((["clear", "screen"], "cls")),
        ((["change", "password"], "net user %USERNAME% *")),
        ((["list", "services"], "sc query type= service state= all")),
        ((["start", "service"], "net start <service>")),
        ((["stop", "service"], "net stop <service>")),
        ((["restart", "service"], "net stop <service> & net start <service>")),
        ((["status", "service"], "sc query <service>")),
        ((["list", "groups"], "net localgroup")),
        ((["add", "user"], "net user <username> /add")),
        ((["delete", "user"], "net user <username> /delete")),
        ((["list", "mounted"], "mountvol")),
        ((["show", "env"], "set")),
    ]
    for keywords, command in rules:
        if all(word in cmd for word in keywords):
            return command
    return f'echo windows: {nl_cmd}'
    